
name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
  trivy-scan:
    name: trivy-scan
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'json'
          output: 'trivy-results.json'
  git-commands:
    name: using git
    runs-on: ubuntu-latest
    steps:
      - name: git difference
        run: git log
  Visualising-files:
    name: viewing path and files
    runs-on: ubuntu-latest
    steps:
      - name: viewing the current directory
        run: pwd
      - name: viewing the files
        run: ls
      - name: viewing the trivy-results.json file
        run: cat trivy-results.json
        
  
          
      

