
name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
  trivy-scan:
    name: trivy-scan
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'json'
#           output: 'trivy-results.json'

#       - name: uploading the json as an artifact
#         uses: actions/upload-artifact@v3.1.0
#         with:
#           name: my-artifact
#           path: my-artifact.json
  uploading-artifact:
    name: uploading artifacts
    runs-on: ubuntu-latest
    needs: trivy-scan
    steps:
      - name: creating folder
        run: mkdir downloads
      - name: creating files
        run: | 
          cd downloads
          echo: 'hello' hello.json
          cd ..
      - name: upolading artifact
        uses: actions/checkout@v2
        with:
          name: my-artifact
          path: downloads
          
      

