
name: CI
on: [push]

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: pwd
      - name: new file creation
        run: |
          "hello" >> new.txt
      - name: files
        run: ls
      - name: path
        run: |
          pwd
          echo pwd
      - name: environmental variable
        run: |
          if $env.GITHUB_ACTIONS
          then
            echo inside githubactions
          else
            echo outside githubactions
          fi
          
#       - name: git configurations
#         run: |
#           git --version
#           git diff composer.json
          
  
          
      

