
name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
  git-commands:
    name: using git
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: git initialisation
        run: git init
      - name: git difference
        run: git log
  Visualising-files:
    name: viewing path and files
    runs-on: ubuntu-latest
    steps:
      - name: viewing the current directory
        run: pwd
      - name: viewing the files
        run: ls
      - name: viewing the trivy-results.json file
        run: cat trivy-results.json
        
  
          
      

