
name: CI
on: [push]

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: pwd
      - name: files
        run: ls
      - name: path
        run: |
          pwd
          echo pwd
      - name: environmental variable
        run: |
          if $env.GITHUB_ACTIONS
          then
            echo inside githubactions
          else
            echo outside githubactions
          fi
#       - name: chcking if else
#         run: |
#           $sample = "hello"
#           if [$sample = "temp"]
#           then
#             echo "condition satisfied"
#           else
#             echo "not done"
#           fi
          
#       - name: git configurations
#         run: |
#           git --version
#           git diff composer.json
          
  
          
      

