
name: CI
on: 
  workflow_call: 
    inputs:
      TEMP: 
        type: string
        default: "temp"

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: pwd
      - name: files
        run: ls
      - name: chcking if else
        run: |
          sample = $inputs.TEMP
          if [$sample = "temp"]
          then
            echo "condition satisfied"
          else
            echo "not done"
          fi
          
#       - name: git configurations
#         run: |
#           git --version
#           git diff composer.json
          
  
          
      

